image: node:lts

cache:
  paths:
    - node_modules/

build:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  image: node:latest
  stage: build
  tags:
    - docker
  script:
    - npm install
    - node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod
  artifacts:
    paths:
    - dist/

deploy_staging:
  image: socolin/naheulbook-deploy
  stage: deploy
  tags:
    - docker
  script:
    - mkdir --mode=700 -p ~/.ssh
    - cp $SSH_KNOWN_HOSTS ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - chmod 600 $SSH_RSYNC_KEY $SSH_DEPLOY_KEY
    - rsync -e "ssh -i $SSH_RSYNC_KEY" -a dist/ naheulbook@naheulbook.fr:/frontend
    - ssh -i $SSH_DEPLOY_KEY naheulbook@naheulbook.fr deploy
  environment:
    name: staging
  except:
    variables:
      - $DEV

deploy_prod:
  image: socolin/naheulbook-deploy
  stage: deploy
  tags:
    - docker
  script:
    - mkdir --mode=700 -p ~/.ssh
    - cp $SSH_KNOWN_HOSTS ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - chmod 600 $SSH_RSYNC_KEY $SSH_DEPLOY_KEY
    - rsync -e "ssh -i $SSH_RSYNC_KEY" -a dist/ naheulbook@naheulbook.fr:/frontend
    - ssh -i $SSH_DEPLOY_KEY naheulbook@naheulbook.fr deploy
  environment:
    name: production
  when: manual
  except:
    variables:
      - $DEV
