stages:
  - build
  - test
  - publish
  - deploy

cache:
  key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME"
  paths:
    - .nuget/

.dotnet_template: &dotnet_build
  image: mcr.microsoft.com/dotnet/core/sdk:5.0

build:
  <<: *dotnet_build
  tags:
    - docker
  stage: build
  script:
    - "dotnet restore --packages ./.nuget"
    - "dotnet build --no-restore -c Release"

test:
  <<: *dotnet_build
  tags:
    - docker
  stage: test
  script:
    - "dotnet restore --packages ./.nuget"
    - "dotnet test Naheulbook.Core.Tests.Unit --no-restore"
    - "dotnet test Naheulbook.Web.Tests.Unit --no-restore"

publish:
  <<: *dotnet_build
  tags:
    - docker
  stage: publish
  script:
    - "dotnet restore --packages ./.nuget"
    - "dotnet publish --no-restore -c Release Naheulbook.Web"
    - "dotnet publish --no-restore -c Release Naheulbook.DatabaseMigrator.Cli"
  artifacts:
    name: "Build"
    paths:
      - Naheulbook.Web/bin/Release/publish/
      - Naheulbook.DatabaseMigrator.Cli/bin/Release/publish/

deploy_staging:
  image: socolin/naheulbook-deploy
  tags:
    - docker
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_RSYNC_DBMIGRATOR_PREPROD_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - rsync -a Naheulbook.DatabaseMigrator.Cli/bin/Release/publish/ naheulbook@naheulbook.fr:/preprod_migrator
    - ssh-add -D
    - echo "$SSH_RSYNC_WEB_PREPROD_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - rsync -a Naheulbook.Web/bin/Release/publish/ naheulbook@naheulbook.fr:/preprod
    - ssh-add -D
    - echo "$SSH_DEPLOY_PREPROD_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh naheulbook@naheulbook.fr deploy
  environment:
    name: staging
  except:
    variables:
      - $DEV
  only:
    - master

deploy_prod:
  image: socolin/naheulbook-deploy
  tags:
    - docker
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_RSYNC_DBMIGRATOR_PROD_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - rsync -a Naheulbook.DatabaseMigrator.Cli/bin/Release/publish/ naheulbook@naheulbook.fr:/prod_migrator
    - ssh-add -D
    - echo "$SSH_RSYNC_WEB_PROD_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - rsync -a Naheulbook.Web/bin/Release/publish/ naheulbook@naheulbook.fr:/prod
    - ssh-add -D
    - echo "$SSH_DEPLOY_PROD_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh naheulbook@naheulbook.fr deploy
  environment:
    name: prod
  when: manual
  except:
    variables:
      - $DEV
  only:
    - master
