stages:
  - build
  - test
  - publish
  - deploy

cache:
  key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME"
  paths:
    - .nuget/

.dotnet_template: &dotnet_build
  image: microsoft/dotnet:latest

build:
  <<: *dotnet_build
  tags:
    - docker
  stage: build
  script:
    - "dotnet restore --packages ./.nuget"
    - "dotnet build --no-restore -c Release"

test:
  <<: *dotnet_build
  tags:
    - docker
  stage: test
  script:
    - "dotnet restore --packages ./.nuget"
    - "dotnet test Naheulbook.Core.Tests.Unit --no-restore"
    - "dotnet test Naheulbook.Web.Tests.Unit --no-restore"

publish:
  <<: *dotnet_build
  tags:
    - docker
  stage: publish
  script:
    - "dotnet restore --packages ./.nuget"
    - "dotnet publish --no-restore -c Release Naheulbook.Web"
    - "dotnet publish --no-restore -c Release Naheulbook.DatabaseMigrator"
  artifacts:
    name: "Build"
    paths:
      - Naheulbook.Web/bin/Release/publish/
      - Naheulbook.DatabaseMigrator/bin/Release/publish/

deploy_staging:
  image: ubuntu
  tags:
    - docker
  stage: deploy
  script:
    - apt-get update -y && apt-get install rsync
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_RSYNC_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SSH_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync -e 'ssh -i rsync_key' -a Naheulbook.DatabaseMigrator/bin/Release/publish/ naheulbook@naheulbook.fr:/preprod_migrator
    - rsync -e 'ssh -i rsync_key' -a Naheulbook.Web/bin/Release/publish/ naheulbook@naheulbook.fr:/preprod
    - ssh -i deploy_key naheulbook@naheulbook.fr deploy
  environment:
    name: staging
  except:
    variables:
      - $DEV
  only:
    - master

deploy_prod:
  image: ubuntu
  tags:
    - docker
  stage: deploy
  script:
    - apt-get update -y && apt-get install rsync 
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_RSYNC_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SSH_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync -e 'ssh -i rsync_key' -a Naheulbook.DatabaseMigrator/bin/Release/publish/ naheulbook@naheulbook.fr:/prod_migrator
    - rsync -e 'ssh -i rsync_key' -a Naheulbook.Web/bin/Release/publish/ naheulbook@naheulbook.fr:/prod
    - ssh -i deploy_key naheulbook@naheulbook.fr deploy
  environment:
    name: prod
  when: manual
  except:
    variables:
      - $DEV
  only:
    - master