stages:
  - build
  - test
  - publish
  - deploy

cache:
  key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME"
  paths:
    - .nuget/

.dotnet_template: &dotnet_build
  image: mcr.microsoft.com/dotnet/sdk:7.0

build:
  <<: *dotnet_build
  tags:
    - docker
  stage: build
  script:
    - "dotnet restore --packages ./.nuget"
    - "dotnet build --no-restore -c Release"

test:
  <<: *dotnet_build
  tags:
    - docker
  stage: test
  script:
    - "dotnet restore --packages ./.nuget"
    - "dotnet test tests/Naheulbook.Core.Tests.Unit --no-restore"
    - "dotnet test tests/Naheulbook.Web.Tests.Unit --no-restore"

publish:
  <<: *dotnet_build
  tags:
    - docker
  stage: publish
  script:
    - "dotnet restore --packages ./.nuget"
    - "dotnet publish --no-restore -c Release src/Naheulbook.Web"
    - "dotnet publish --no-restore -c Release src/Naheulbook.DatabaseMigrator.Cli"
  artifacts:
    name: "Build"
    paths:
      - src/Naheulbook.Web/bin/Release/publish/
      - src/Naheulbook.DatabaseMigrator.Cli/bin/Release/publish/

deploy_staging:
  image: socolin/naheulbook-deploy
  tags:
    - docker
  stage: deploy
  script:
    - mkdir --mode=700 -p ~/.ssh
    - cp $SSH_KNOWN_HOSTS ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - chmod 600 $SSH_RSYNC_DBMIGRATOR_KEY $SSH_RSYNC_WEB_KEY $SSH_DEPLOY_KEY
    - rsync -e "ssh -i $SSH_RSYNC_DBMIGRATOR_KEY" -a src/Naheulbook.DatabaseMigrator.Cli/bin/Release/publish/ naheulbook@naheulbook.fr:/preprod_migrator
    - rsync -e "ssh -i $SSH_RSYNC_WEB_KEY" -a src/Naheulbook.Web/bin/Release/publish/ naheulbook@naheulbook.fr:/preprod
    - ssh -i $SSH_DEPLOY_KEY naheulbook@naheulbook.fr deploy
  environment:
    name: staging
  except:
    variables:
      - $DEV
  only:
    - master

deploy_prod:
  image: socolin/naheulbook-deploy
  tags:
    - docker
  stage: deploy
  script:
    - mkdir --mode=700 -p ~/.ssh
    - cp $SSH_KNOWN_HOSTS ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - chmod 600 $SSH_RSYNC_DBMIGRATOR_KEY $SSH_RSYNC_WEB_KEY $SSH_DEPLOY_KEY
    - rsync -e "ssh -i $SSH_RSYNC_DBMIGRATOR_KEY" -a src/Naheulbook.DatabaseMigrator.Cli/bin/Release/publish/ naheulbook@naheulbook.fr:/prod_migrator
    - rsync -e "ssh -i $SSH_RSYNC_WEB_KEY" -a src/Naheulbook.Web/bin/Release/publish/ naheulbook@naheulbook.fr:/prod
    - ssh -i $SSH_DEPLOY_KEY naheulbook@naheulbook.fr deploy
  environment:
    name: prod
  when: manual
  except:
    variables:
      - $DEV
  only:
    - master
