// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Naheulbook.Tests.Functional.Functionals
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Origin")]
    public partial class OriginFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Origin.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Origin", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Listing origins")]
        public virtual void ListingOrigins()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listing origins", null, ((string[])(null)));
#line 3
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 4
    testRunner.When("performing a GET to the url \"/api/v2/origins\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 5
    testRunner.Then("the response status code be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 6
    testRunner.And("the response should contains a json array containing the following element identi" +
                    "fied by id", "{\n    \"id\": 6,\n    \"name\": \"Elfe sylvain\",\n    \"description\": \"<p>Les Sylvains so" +
                    "nt les descendants des elfes ayant découvert la Terre de Fangh il y a bien longt" +
                    "emps. Ils ont choisi de fuir la\\ncompagnie des humains pour vivre dans la forêt " +
                    "car ils s\'y sentaient bien, et que tout le monde y est gentil. Ils ont une\\ncult" +
                    "ure particulière, des styles de vie particuliers et sont enclins à la niaiserie " +
                    "et à l\'innocence.\\n</p>\",\n    \"playerDescription\": \"Je suis né au milieu des arb" +
                    "res, et j\'y ai passé la plus grande partie de mon enfance. Mes parents étaient g" +
                    "entils, tout comme nos amis les animaux de la forêt, et nos voisins qui cueillai" +
                    "ent souvent des framboises avec nous. Dans ma famille on tire à l\'arc, on aime l" +
                    "es poneys et on ne fait pas de mal aux gens quand on a le choix. Nous aimons l\'a" +
                    "rt, les chansons, sentir le vent dans nos cheveux propres.\",\n    \"playerSummary\"" +
                    ": \"Personnage doué en milieu naturel, dangereux sur les attaques à distance. Pas" +
                    " d\'arme à 2 mains.\\r\\nTransport de charges limité à 10 kilos – Sens développés, " +
                    "nyctalopie totale. Armure max : PR4.\",\n    \"maxLoad\": 10,\n    \"maxArmorPR\": 4,\n " +
                    "   \"advantage\": \"Peut utiliser n’importe quelle forme d\'objet enchanté (et parch" +
                    "emin avec « érudition » s\'il choisit un métier).\\nExcellente vue, bon odorat, ny" +
                    "ctalopie totale.\",\n    \"baseEV\": 25,\n    \"baseEA\": null,\n    \"bonusAT\": null,\n  " +
                    "  \"bonusPRD\": null,\n    \"diceEVLevelUp\": 6,\n    \"size\": \"Taille humaine standard" +
                    ", généralement plus mince et plus élancé.\",\n    \"flags\": [],\n    \"speedModifier\"" +
                    ": 20,\n    \"skillIds\": [\n        15,\n        36,\n        39,\n        47,\n        " +
                    "48\n    ],\n    \"availableSkillIds\": [\n        17,\n        19,\n        31,\n       " +
                    " 35,\n        38,\n        46\n    ],\n    \"infos\": [\n        {\n            \"title\":" +
                    " \"Les Sylvains et les armes\",\n            \"description\": \"ils sont assez évolués" +
                    " pour utiliser toute forme d\'arme, mais leur côté précieux et fragile les\\nrend " +
                    "quelque peu réfractaire à l\'utilisation des armes à deux mains. Considérées comm" +
                    "e des « armes de bourrin » dans toute\\nla Terre de Fangh, elles donne un côté be" +
                    "stial et fait souvent jaillir le sang à plusieurs mètres à la ronde, ce qui peut" +
                    " tacher\\nles vêtements. Ainsi, les Sylvains n\'utilisent jamais d\'armes à deux ma" +
                    "ins.\"\n        },\n        {\n            \"title\": \"Les Sylvains et l\'équipement\",\n" +
                    "            \"description\": \"d\'un naturel soigneux et délicat, ce personnage ne v" +
                    "eut pas se transformer en dromadaire. Il\\nrefusera donc de porter de lourdes cha" +
                    "rges ou de s\'encombrer, tout simplement parce que ce n\'est pas dans sa nature. I" +
                    "l\\nn\'aimera pas non plus se trouver engoncé dans une boîte de conserve, et va pr" +
                    "éférer le port de plusieurs pièces d\'armure de\\ncuir ou de tissu à celui d\'une p" +
                    "ièce d\'armure métallique ou renforcée.\"\n        },\n        {\n            \"title\"" +
                    ": \"L\'Elfe Sylvain et la magie\",\n            \"description\": \"il n\'a pas d\'aptitud" +
                    "e à la magie par manque d\'imagination et d\'intelligence, la plupart du temps,\\nm" +
                    "ais il n\'y est pas réfractaire et trouve généralement cela merveilleux. Il est t" +
                    "out à fait dans le caractère d\'un elfe\\nd\'utiliser n\'importe quel objet magique," +
                    " ou tout type de matériel béni pour peu que ça ne soit pas contraire à sa religi" +
                    "on\\n(dans le cas où il serait prêtre). En revanche, il ne sera capable d\'utilise" +
                    "r les parchemins que s\'il sait lire. Note : Certains\\nElfes Sylvains d\'ailleurs " +
                    "font des études particulières pour être capable de lancer eux mêmes des sortilèg" +
                    "es, mais les gens\\ns\'en méfient.\"\n        },\n        {\n            \"title\": \"Les" +
                    " armes de jet\",\n            \"description\": \"l\'arme de jet de prédilection des Sy" +
                    "lvains est l\'arc. La plupart des autres armes de jet sont moches,\\nencombrantes," +
                    " lourdes, peu pratiques ou fabriquées par les Nains. Ils ne sont pas mauvais au " +
                    "poignard également.\"\n        }\n    ],\n    \"bonuses\": [\n        {\n            \"de" +
                    "scription\": \"+1 point au CHARISME au passage des niveaux 2 et 3\",\n            \"f" +
                    "lags\": [\n                {\n                    \"type\": \"CHA_+1_LVL2_LVL3\",\n     " +
                    "               \"data\": null\n                }\n            ]\n        }\n    ],\n   " +
                    " \"requirements\": [\n        {\n            \"stat\": \"CHA\",\n            \"min\": 12,\n " +
                    "           \"max\": null\n        },\n        {\n            \"stat\": \"AD\",\n          " +
                    "  \"min\": 10,\n            \"max\": null\n        },\n        {\n            \"stat\": \"F" +
                    "O\",\n            \"min\": null,\n            \"max\": 11\n        }\n    ],\n    \"restric" +
                    "ts\": [\n        {\n            \"description\": \"pas d’aptitudes à la magie (métier " +
                    "de mage ou prêtrise)\",\n            \"flags\": [\n                {\n                " +
                    "    \"type\": \"NO_MAGIC\",\n                    \"data\": null\n                }\n     " +
                    "       ]\n        },\n        {\n            \"description\": \"ne peut utiliser les a" +
                    "rmes à 2 mains\",\n            \"flags\": [\n                {\n                    \"d" +
                    "ata\": \"ARME_BOURRIN\",\n                    \"type\": \"NO_SKILL\"\n                }\n " +
                    "           ]\n        },\n        {\n            \"description\": \"transport de charg" +
                    "e limitée à 10 kilos\",\n            \"flags\": []\n        },\n        {\n            " +
                    "\"description\": \"n’utilise pas d’armure supérieure à PR4 (sauf magique)\",\n       " +
                    "     \"flags\": []\n        }\n    ]\n}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
