version: "3.9"
services:
  naheulbook_mysql:
    image: mariadb:10.9
    networks:
      naheulbook_prod:
        ipv4_address: 172.11.1.2
    environment:
      MYSQL_ROOT_PASSWORD: PUT_SOME_RANDOM_HERE
    restart: unless-stopped
    volumes:
      - ./mysql/data:/var/lib/mysql
  naheulbook_redis:
    networks:
      naheulbook_prod:
        ipv4_address: 172.11.1.3
    image: redis:latest
    restart: unless-stopped
  naheulbook_init_db:
    image: ghcr.io/socolin/naheulbook-db-migrator:master
    networks:
      naheulbook_prod:
        ipv4_address: 172.11.1.5
    depends_on:
      - naheulbook_redis
      - naheulbook_mysql
    volumes:
      - ./appsettings.local.json:/app/appsettings.local.json
    environment:
      operation: "migrate"
  naheulbook:
    image: ghcr.io/socolin/naheulbook:master
    user: "1001:1000"
    depends_on:
      naheulbook_init_db:
        condition: service_completed_successfully
    networks:
      naheulbook_prod:
        ipv4_address: 172.11.1.4
    restart: unless-stopped
    volumes:
      - ./map_images:/map_images
      - /var/run/naheulbook/:/var/run/naheulbook
      - ./appsettings.local.json:/app/appsettings.local.json
    environment:
      DisplayExceptionFields: true
      socketPermission: 770
      socket: /var/run/naheulbook/prod.sock
      MapImage__OutputDirectory: "/map_images"

networks:
  naheulbook_prod:
    driver: bridge
    ipam:
     config:
       - subnet: 172.11.1.0/24
         gateway: 172.11.1.1
